---
- hosts: aws_ec2
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/ansible/ansible_ssh_key.pem"
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
 
